dist: xenial
language: cpp
compiler: clang
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
before_script:
- sudo apt update
- sudo apt install libboost-test-dev libspdlog-dev -y
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile
deploy:
 provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
