dist: xenial
language: cpp
compiler: clang
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - graphviz
before_script:
- sudo apt update
- sudo apt install libboost-test-dev libspdlog-dev -y
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile
deploy: 
  provider: script
  skip_cleanup: true
  script:
  - curl -T cmake-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ubesSveta:$BINTRAY_API_KEY "https://api.bintray.com/content/bessveta/otus-cpp/homework1/print_ip/cmake-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"

deploy:
 provider: pages
 skip_cleanup: true
 local_dir: html
 github_token: $GH_REPO_TOKEN
 keep_history: true
 on:
   branch: master
